title: RAJINI PARIMALA
logo: https://github.com/Rajiniparimala/minimal/blob/master/assets/img/IMG-3553.jpg
description: My projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
